version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./src:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8876:80"
    depends_on:
      - app
    container_name: project_nginx  

  app:
    build:
      context: .
      dockerfile: _docker/app/.Dockerfile
    volumes:
      - ./src:/var/www
    user: "1000:1000"  
    container_name: project_app

  mysql:
    image: mysql:8.0
    volumes:
    - db_mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_DATABASE=laravel"
    ports:
    - "33061:3306"
     
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=user
      - PMA_PASSWORD=secret
      - UPLOAD_LIMIT=64M
    restart: always
    ports:
      - 8081:80
      
  node:
    image: node:18-alpine
    ports:
        - "3000:3000"
    volumes:
    - ./src:/var/www
    working_dir: /var/www
    tty: true

volumes:
  db_mysql: